### PR TITLE
Milestone 5 events

### PR DESCRIPTION
**Pull request by KerronKing**
In this milestone, I:
- Initialized the App component's state in the constructor with three properties: total, next and operation and set them each to null.
- Implemented the handleClick function as specified.
- Used the onClick event to attach the handleClick event to the button.

### CODE REVIEW

**Review by azdrenymeri — CHANGES_REQUESTED** [review]
### Hi @KerronKing :wave: 
#### There is only one thing left.
 - [x] Error handling
I tried to divide a number by zero and this happend:
scr
### Kindly fix it and add it for another review

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED 

Hi @KerronKing good job on this implementation everything is coming along fine, I just noticed one little thing. :+1: 

- When a calculation is made and the answer is displayed, if the user then presses another number button it should ideally wipe out the display and input that number, but your current implementation attaches the new number to the end of the previously calculated answer. 
For this, you want to look in your if conditions in App.js

Please work on that, **and request for another review when done** :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED 

Hi @KerronKing good job on making that change, it works but it seems it messed up some other things, I attached a video so you can see it :slightly_smiling_face:  [see this](https://www.loom.com/share/d62ec589c1c342a49f61ece339a3de14)

- a calculated value cannot be used as an operand for a new calculation, example, do 9 + 6,  you should get 15 now do + 4, nothing happens at all 

please look into that, and resubmit for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

**Comment by bellom** [comment]
Hello @KerronKing , kindly fix the merge conflict because am unable to run `git checkout milestone-5-events`

**Review by bellom — APPROVED** [review]
## Hi @KerronKing  :clap: 

**Great work making all the necessary corrections from the previous review, App works fine now 👍 **

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 


**NOTE:** 
You added just one line in the `.eslintrc.json` file 😄, avoid this in the next project.
image
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/


Kindly 
Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
